import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

function generateVacancyText(answers: string[]) {
  return (
    <div className="bg-white rounded-xl shadow p-8 space-y-6">
      <h2 className="text-2xl font-bold mb-4">Вакансия</h2>
      <section>
        <h3 className="text-lg font-semibold mb-1 text-blue-700">О компании и проекте</h3>
        <p className="text-neutral-800">{answers[0] || '-'}</p>
      </section>
      <section>
        <h3 className="text-lg font-semibold mb-1 text-blue-700">Стек и технологии</h3>
        <ul className="list-disc pl-5 text-neutral-800">
          {answers[1].split(/[\n,;]+/).map((item, i) => <li key={i}>{item.trim()}</li>)}
        </ul>
      </section>
      <section>
        <h3 className="text-lg font-semibold mb-1 text-blue-700">Условия</h3>
        <ul className="list-disc pl-5 text-neutral-800">
          {answers[2].split(/[\n,;]+/).map((item, i) => <li key={i}>{item.trim()}</li>)}
        </ul>
      </section>
      <section>
        <h3 className="text-lg font-semibold mb-1 text-blue-700">Требования</h3>
        <ul className="list-disc pl-5 text-neutral-800">
          {answers[3].split(/[\n,;]+/).map((item, i) => <li key={i}>{item.trim()}</li>)}
        </ul>
      </section>
      <section>
        <h3 className="text-lg font-semibold mb-1 text-blue-700">Чем предстоит заниматься</h3>
        <ul className="list-disc pl-5 text-neutral-800">
          {answers[4].split(/[\n,;]+/).map((item, i) => <li key={i}>{item.trim()}</li>)}
        </ul>
      </section>
    </div>
  );
}
